name = "SeqLoggers"
uuid = "5370ec29-8137-43b2-8ce7-bd26b38685e0"
authors = ["Ueli Wechsler <ueli.wechsler@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
